//State de productos

export const OBTENER_PRODUCTOS_EXITO = 'OBTERNER_PRODUCTOS_EXITO';

export const OBTENER_PRODUCTOS_INICIO = 'OBTENER_PRODUCTOS_INCIO';

//state para el pedido

export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';